### ISSUE TITLE
[FIX] grammatical error on "About me"

### ISSUE THREAD

**Issue by AbbeyIT** [kiritocode1/kiritocode1.github.io#9]
I suggest fixing the "About me" section grammatical errors for easy reading and accessibility. The "About me" section is one of the first things you will see on your website, and I think it is important to give importance to fixing it.

**Comment by kiritocode1** [comment]
# Sure  @AbbeyIT  , 😊 please suggest changes right here or make a PR .

**Comment by AbbeyIT** [comment]
I've seen that your code is on React and I still don't know how to use React. So, I will just suggest it here. 

**Before**
hello there , im Aryan kathawale , a 19 yr old Computer Programmer based in India, I focus Mostly on  Open Source projects and cool technologies , i believe and work towards a society based on Curiosity and Collaboration.
**After**
Hello there, I'm Aryan Kathawale, a 19-year-old computer programmer based in India. I focus mainly on open source projects and cool technologies. I believe and work towards a society based on curiosity and collaboration.

**Comment by kiritocode1** [comment]
### thank You soo much @AbbeyIT  , 😊  . I will make the changes accordingly  and continue to follow  this websites . I am planning to make interactive stuff with css for react

**Comment by kiritocode1** [comment]
Youre an absolute  Chad :)

**Comment by AbbeyIT** [comment]
You're welcome. I like your website, so I'm highly interested in contributing to it @kiritocode1 💯

**Comment by kiritocode1** [comment]
Thank you and dur to your suggestion i got an idea 💡 , i have started my blog and wikk include interactive blogs on react, and things like that 
But rn checkout https://kiritocode1.github.io/how_i_made_this_website/
